/* Generated by wayland-scanner 1.13.0 */

#ifndef WESTON_SCREENSHOOTER_SERVER_PROTOCOL_H
#define WESTON_SCREENSHOOTER_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_weston_screenshooter The weston_screenshooter protocol
 * @section page_ifaces_weston_screenshooter Interfaces
 * - @subpage page_iface_weston_screenshooter - 
 * - @subpage page_iface_weston_display_coinfig - weston dislay config
 */
struct weston_display_coinfig;
struct weston_screenshooter;
struct wl_buffer;
struct wl_output;

/**
 * @page page_iface_weston_screenshooter weston_screenshooter
 * @section page_iface_weston_screenshooter_api API
 * See @ref iface_weston_screenshooter.
 */
/**
 * @defgroup iface_weston_screenshooter The weston_screenshooter interface
 */
extern const struct wl_interface weston_screenshooter_interface;
/**
 * @page page_iface_weston_display_coinfig weston_display_coinfig
 * @section page_iface_weston_display_coinfig_desc Description
 *
 * Internal testing facilities for the weston compositor.
 *
 * @section page_iface_weston_display_coinfig_api API
 * See @ref iface_weston_display_coinfig.
 */
/**
 * @defgroup iface_weston_display_coinfig The weston_display_coinfig interface
 *
 * Internal testing facilities for the weston compositor.
 *
 */
extern const struct wl_interface weston_display_coinfig_interface;

/**
 * @ingroup iface_weston_screenshooter
 * @struct weston_screenshooter_interface
 */
struct weston_screenshooter_interface {
	/**
	 */
	void (*shoot)(struct wl_client *client,
		      struct wl_resource *resource,
		      struct wl_resource *output,
		      struct wl_resource *buffer);
};

#define WESTON_SCREENSHOOTER_DONE 0

/**
 * @ingroup iface_weston_screenshooter
 */
#define WESTON_SCREENSHOOTER_DONE_SINCE_VERSION 1

/**
 * @ingroup iface_weston_screenshooter
 */
#define WESTON_SCREENSHOOTER_SHOOT_SINCE_VERSION 1

/**
 * @ingroup iface_weston_screenshooter
 * Sends an done event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
weston_screenshooter_send_done(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, WESTON_SCREENSHOOTER_DONE);
}

#ifndef WESTON_DISPLAY_COINFIG_ERROR_ENUM
#define WESTON_DISPLAY_COINFIG_ERROR_ENUM
enum weston_display_coinfig_error {
	/**
	 * get hdmi modes succ.
	 */
	WESTON_DISPLAY_COINFIG_ERROR_OK = 0,
	/**
	 * get hdmi modes fail.
	 */
	WESTON_DISPLAY_COINFIG_ERROR_FAIL = -1,
};
#endif /* WESTON_DISPLAY_COINFIG_ERROR_ENUM */

/**
 * @ingroup iface_weston_display_coinfig
 * @struct weston_display_coinfig_interface
 */
struct weston_display_coinfig_interface {
	/**
	 */
	void (*GetResource)(struct wl_client *client,
			    struct wl_resource *resource,
			    const char *modes);
	/**
	 */
	void (*GetResource2)(struct wl_client *client,
			     struct wl_resource *resource,
			     struct wl_resource *output,
			     struct wl_resource *modes);
	/**
	 */
	void (*SetMode)(struct wl_client *client,
			struct wl_resource *resource,
			struct wl_resource *output,
			int32_t width,
			int32_t height,
			int32_t refresh,
			int32_t flag,
			int32_t reserved);
};

#define WESTON_DISPLAY_COINFIG_FINISHED 0

/**
 * @ingroup iface_weston_display_coinfig
 */
#define WESTON_DISPLAY_COINFIG_FINISHED_SINCE_VERSION 1

/**
 * @ingroup iface_weston_display_coinfig
 */
#define WESTON_DISPLAY_COINFIG_GETRESOURCE_SINCE_VERSION 1
/**
 * @ingroup iface_weston_display_coinfig
 */
#define WESTON_DISPLAY_COINFIG_GETRESOURCE2_SINCE_VERSION 1
/**
 * @ingroup iface_weston_display_coinfig
 */
#define WESTON_DISPLAY_COINFIG_SETMODE_SINCE_VERSION 1

/**
 * @ingroup iface_weston_display_coinfig
 * Sends an finished event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
weston_display_coinfig_send_finished(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, WESTON_DISPLAY_COINFIG_FINISHED);
}

#ifdef  __cplusplus
}
#endif

#endif
