/* Generated by wayland-scanner 1.13.0 */

#ifndef WESTON_SCREENSHOOTER_CLIENT_PROTOCOL_H
#define WESTON_SCREENSHOOTER_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_weston_screenshooter The weston_screenshooter protocol
 * @section page_ifaces_weston_screenshooter Interfaces
 * - @subpage page_iface_weston_screenshooter - 
 * - @subpage page_iface_weston_display_coinfig - weston dislay config
 */
struct weston_display_coinfig;
struct weston_screenshooter;
struct wl_buffer;
struct wl_output;

/**
 * @page page_iface_weston_screenshooter weston_screenshooter
 * @section page_iface_weston_screenshooter_api API
 * See @ref iface_weston_screenshooter.
 */
/**
 * @defgroup iface_weston_screenshooter The weston_screenshooter interface
 */
extern const struct wl_interface weston_screenshooter_interface;
/**
 * @page page_iface_weston_display_coinfig weston_display_coinfig
 * @section page_iface_weston_display_coinfig_desc Description
 *
 * Internal testing facilities for the weston compositor.
 *
 * @section page_iface_weston_display_coinfig_api API
 * See @ref iface_weston_display_coinfig.
 */
/**
 * @defgroup iface_weston_display_coinfig The weston_display_coinfig interface
 *
 * Internal testing facilities for the weston compositor.
 *
 */
extern const struct wl_interface weston_display_coinfig_interface;

/**
 * @ingroup iface_weston_screenshooter
 * @struct weston_screenshooter_listener
 */
struct weston_screenshooter_listener {
	/**
	 */
	void (*done)(void *data,
		     struct weston_screenshooter *weston_screenshooter);
};

/**
 * @ingroup iface_weston_screenshooter
 */
static inline int
weston_screenshooter_add_listener(struct weston_screenshooter *weston_screenshooter,
				  const struct weston_screenshooter_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) weston_screenshooter,
				     (void (**)(void)) listener, data);
}

#define WESTON_SCREENSHOOTER_SHOOT 0

/**
 * @ingroup iface_weston_screenshooter
 */
#define WESTON_SCREENSHOOTER_DONE_SINCE_VERSION 1

/**
 * @ingroup iface_weston_screenshooter
 */
#define WESTON_SCREENSHOOTER_SHOOT_SINCE_VERSION 1

/** @ingroup iface_weston_screenshooter */
static inline void
weston_screenshooter_set_user_data(struct weston_screenshooter *weston_screenshooter, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) weston_screenshooter, user_data);
}

/** @ingroup iface_weston_screenshooter */
static inline void *
weston_screenshooter_get_user_data(struct weston_screenshooter *weston_screenshooter)
{
	return wl_proxy_get_user_data((struct wl_proxy *) weston_screenshooter);
}

static inline uint32_t
weston_screenshooter_get_version(struct weston_screenshooter *weston_screenshooter)
{
	return wl_proxy_get_version((struct wl_proxy *) weston_screenshooter);
}

/** @ingroup iface_weston_screenshooter */
static inline void
weston_screenshooter_destroy(struct weston_screenshooter *weston_screenshooter)
{
	wl_proxy_destroy((struct wl_proxy *) weston_screenshooter);
}

/**
 * @ingroup iface_weston_screenshooter
 */
static inline void
weston_screenshooter_shoot(struct weston_screenshooter *weston_screenshooter, struct wl_output *output, struct wl_buffer *buffer)
{
	wl_proxy_marshal((struct wl_proxy *) weston_screenshooter,
			 WESTON_SCREENSHOOTER_SHOOT, output, buffer);
}

#ifndef WESTON_DISPLAY_COINFIG_ERROR_ENUM
#define WESTON_DISPLAY_COINFIG_ERROR_ENUM
enum weston_display_coinfig_error {
	/**
	 * get hdmi modes succ.
	 */
	WESTON_DISPLAY_COINFIG_ERROR_OK = 0,
	/**
	 * get hdmi modes fail.
	 */
	WESTON_DISPLAY_COINFIG_ERROR_FAIL = -1,
};
#endif /* WESTON_DISPLAY_COINFIG_ERROR_ENUM */

/**
 * @ingroup iface_weston_display_coinfig
 * @struct weston_display_coinfig_listener
 */
struct weston_display_coinfig_listener {
	/**
	 */
	void (*finished)(void *data,
			 struct weston_display_coinfig *weston_display_coinfig);
};

/**
 * @ingroup iface_weston_display_coinfig
 */
static inline int
weston_display_coinfig_add_listener(struct weston_display_coinfig *weston_display_coinfig,
				    const struct weston_display_coinfig_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) weston_display_coinfig,
				     (void (**)(void)) listener, data);
}

#define WESTON_DISPLAY_COINFIG_GETRESOURCE 0
#define WESTON_DISPLAY_COINFIG_GETRESOURCE2 1
#define WESTON_DISPLAY_COINFIG_SETMODE 2

/**
 * @ingroup iface_weston_display_coinfig
 */
#define WESTON_DISPLAY_COINFIG_FINISHED_SINCE_VERSION 1

/**
 * @ingroup iface_weston_display_coinfig
 */
#define WESTON_DISPLAY_COINFIG_GETRESOURCE_SINCE_VERSION 1
/**
 * @ingroup iface_weston_display_coinfig
 */
#define WESTON_DISPLAY_COINFIG_GETRESOURCE2_SINCE_VERSION 1
/**
 * @ingroup iface_weston_display_coinfig
 */
#define WESTON_DISPLAY_COINFIG_SETMODE_SINCE_VERSION 1

/** @ingroup iface_weston_display_coinfig */
static inline void
weston_display_coinfig_set_user_data(struct weston_display_coinfig *weston_display_coinfig, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) weston_display_coinfig, user_data);
}

/** @ingroup iface_weston_display_coinfig */
static inline void *
weston_display_coinfig_get_user_data(struct weston_display_coinfig *weston_display_coinfig)
{
	return wl_proxy_get_user_data((struct wl_proxy *) weston_display_coinfig);
}

static inline uint32_t
weston_display_coinfig_get_version(struct weston_display_coinfig *weston_display_coinfig)
{
	return wl_proxy_get_version((struct wl_proxy *) weston_display_coinfig);
}

/** @ingroup iface_weston_display_coinfig */
static inline void
weston_display_coinfig_destroy(struct weston_display_coinfig *weston_display_coinfig)
{
	wl_proxy_destroy((struct wl_proxy *) weston_display_coinfig);
}

/**
 * @ingroup iface_weston_display_coinfig
 */
static inline void
weston_display_coinfig_GetResource(struct weston_display_coinfig *weston_display_coinfig, const char *modes)
{
	wl_proxy_marshal((struct wl_proxy *) weston_display_coinfig,
			 WESTON_DISPLAY_COINFIG_GETRESOURCE, modes);
}

/**
 * @ingroup iface_weston_display_coinfig
 */
static inline void
weston_display_coinfig_GetResource2(struct weston_display_coinfig *weston_display_coinfig, struct wl_output *output, struct wl_buffer *modes)
{
	wl_proxy_marshal((struct wl_proxy *) weston_display_coinfig,
			 WESTON_DISPLAY_COINFIG_GETRESOURCE2, output, modes);
}

/**
 * @ingroup iface_weston_display_coinfig
 */
static inline void
weston_display_coinfig_SetMode(struct weston_display_coinfig *weston_display_coinfig, struct wl_output *output, int32_t width, int32_t height, int32_t refresh, int32_t flag, int32_t reserved)
{
	wl_proxy_marshal((struct wl_proxy *) weston_display_coinfig,
			 WESTON_DISPLAY_COINFIG_SETMODE, output, width, height, refresh, flag, reserved);
}

#ifdef  __cplusplus
}
#endif

#endif
