/* Generated by wayland-scanner 1.13.0 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface wl_buffer_interface;
extern const struct wl_interface wl_output_interface;

static const struct wl_interface *types[] = {
	NULL,
	&wl_output_interface,
	&wl_buffer_interface,
	&wl_output_interface,
	&wl_buffer_interface,
	&wl_output_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};

static const struct wl_message weston_screenshooter_requests[] = {
	{ "shoot", "oo", types + 1 },
};

static const struct wl_message weston_screenshooter_events[] = {
	{ "done", "", types + 0 },
};

WL_EXPORT const struct wl_interface weston_screenshooter_interface = {
	"weston_screenshooter", 1,
	1, weston_screenshooter_requests,
	1, weston_screenshooter_events,
};

static const struct wl_message weston_display_coinfig_requests[] = {
	{ "GetResource", "s", types + 0 },
	{ "GetResource2", "oo", types + 3 },
	{ "SetMode", "oiiiii", types + 5 },
};

static const struct wl_message weston_display_coinfig_events[] = {
	{ "finished", "", types + 0 },
};

WL_EXPORT const struct wl_interface weston_display_coinfig_interface = {
	"weston_display_coinfig", 1,
	3, weston_display_coinfig_requests,
	1, weston_display_coinfig_events,
};

